version: '3.8'

services:
  llm:
    image: huggingface/text-generation-inference:latest
    ports:
      - "8080:80"
    volumes:
      - ./orchestrator/outputs:/outputs
    environment:
      - MODEL_ID=deepseek-ai/deepseek-r1-distill-qwen-14b
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  tts:
    image: synesthesiam/opentts:latest
    ports:
      - "5500:5500"
    volumes:
      - ./orchestrator/outputs:/outputs
